### ISSUE TITLE
Some basic mathematical functions are missing

### ISSUE THREAD

**Issue by JustWhit3** [sbesada/python.math.expression.parser.pymep#1]
Dear developers,

This tool is really excellent, in fact I was searching exactly something like this. However, there is a small problem: some of the elementary mathematical functions are not supported, i.e.: `pow` and `exp`. Without them, it would be impossible for me to use this tool, since I have to deal with complex number expressions which involve also this functions.

Hope you will fix this lack soon because, within this, the tool would be perfect!

Thanks.

**Comment by sbesada** [comment]
Hi Gianluca,

The function pow and exp are supported, I send you an example of pow = ^
and exp = e. It similar to matlab and Octave

eval("(2.35*e^(-3)*x)",2)

Regards

**Comment by JustWhit3** [comment]
Hi sbesada,

Yes, I seen them, but I was meaning something related to the "real" way of representing these functions in Python, i.e.: pow instead of ^ and exp instead of e; since, unfortunately, without the right definition I cannot be able to use this tool in my project.

**Comment by sbesada** [comment]
Hi Gianluca,

Before calling to pymep (this library) replace "pow" by "^" and "exp" by "e" and you solve the problem, you can do it inside my library or before. If you try to evalute the expression "2+ pow(2,3)" like the math fuction, you need to know that "pow(2,3)" is not a left - right function and this parser is a left -righ parser that could evaluate the expression "2 pow 3" or 2pow(3), those expressions are equivalent to  2^3 or 2 ^(3). You only need to replace "pow" by "^"

**Comment by JustWhit3** [comment]
Ok thank you very much

**Comment by sbesada** [comment]
You can handle pow(2,3) like external function. For instance in real parser realParser.py line 185  add elif function == "pow":
                   new_fx == 2,3 --> do split 
                   and return value math.pow(2,3)
